(function ($) {
    "use strict";

    $.fn.fileinputLocales['ar'] = {
        fileSingle: 'مستند',
        filePlural: 'مستندات',
        browseLabel: ' اختيار المستند للتحميل &hellip;',
        removeLabel: 'إزالة',
        removeTitle: 'إزالة المستندات المختارة',
        cancelLabel: 'إلغاء',
        cancelTitle: 'إلغاء',
        uploadLabel: 'رفع',
        uploadTitle: 'رفع المستندات المختارة',
        msgNo: 'لا',
        msgNoFilesSelected: '',
        msgCancelled: 'ألغيت',
        msgPlaceholder: 'Select {files}...',
        msgZoomModalHeading: 'معاينة تفصيلية',
        msgFileRequired: 'الرجاء اختيار مستند للتحميل',
        msgSizeTooSmall: 'File "{name}" (<b>{size} KB</b>) حجم المستند صغير، يجب ان يتعدى <b>{minSize} KB</b>.',
        msgSizeTooLarge: 'المستند "{name}" (<b>{size} ك.ب</b>) تعدى الحد الأقصى المسموح للتحميل <b>{maxSize} ك.ب</b>.',
        msgFilesTooLess: 'يجب عليك اختيار <b>{n}</b> {files} على الأقل للتحميل.',
        msgFilesTooMany: 'عدد المستندات المختارة للتحميل <b>({n})</b> تعدت الحد الأقصى المسموح به لعدد <b>{m}</b>.',
        msgFileNotFound: 'المستند "{name}" غير موجود!',
        msgFileSecured: 'قيود أمنية تمنع قراءة المستند "{name}".',
        msgFileNotReadable: 'المستند "{name}" غير قابل للقراءة.',
        msgFilePreviewAborted: 'تم إلغاء معاينة المستند "{name}".',
        msgFilePreviewError: 'حدث خطأ أثناء قراءة المستند "{name}".',
        msgInvalidFileName: 'Invalid or unsupported characters in file name "{name}".',
        msgInvalidFileType: 'نوعية غير صالحة للمستند "{name}". فقط هذه النوعيات مدعومة "{types}".',
        msgInvalidFileExtension: 'امتداد غير صالح للمستند "{name}". <br/> فقط هذه المستندات مدعومة  "{extensions}".',
        msgFileTypes: {
            'image': 'صور',
            'html': 'HTML',
            'text': 'text',
            'video': 'video',
            'audio': 'audio',
            'flash': 'flash',
            'pdf': 'PDF',
            'object': 'object'
        },
        msgUploadAborted: 'تم إلغاء رفع المستند',
        msgUploadThreshold: 'Processing...',
        msgUploadBegin: 'Initializing...',
        msgUploadEnd: 'Done',
        msgUploadEmpty: 'No valid data available for upload.',
        msgUploadError: 'Error',
        msgValidationError: 'خطأ التحقق من صحة',
        msgLoading: 'تحميل مستند {index} من {files} &hellip;',
        msgProgress: 'تحميل مستند {index} من {files} - {name} - {percent}% منتهي.',
        msgSelected: '{n} {files} مختار(ة)',
        msgFoldersNotAllowed: 'اسحب وأفلت المستندات فقط! تم تخطي {n} مجلد(ات).',
        msgImageWidthSmall: 'عرض مستند الصورة "{name}" يجب أن يكون على الأقل {size} px.',
        msgImageHeightSmall: 'طول مستند الصورة "{name}" يجب أن يكون على الأقل {size} px.',
        msgImageWidthLarge: 'عرض مستند الصورة "{name}" لا يمكن أن يتعدى {size} px.',
        msgImageHeightLarge: 'طول مستند الصورة "{name}" لا يمكن أن يتعدى {size} px.',
        msgImageResizeError: 'لم يتمكن من معرفة أبعاد الصورة لتغييرها.',
        msgImageResizeException: 'حدث خطأ أثناء تغيير أبعاد الصورة.<pre>{errors}</pre>',
        msgAjaxError: 'Something went wrong with the {operation} operation. Please try again later!',
        msgAjaxProgressError: '{operation} failed',
        ajaxOperations: {
            deleteThumb: 'file delete',
            uploadThumb: 'file upload',
            uploadBatch: 'batch file upload',
            uploadExtra: 'form data upload'
        },
        dropZoneTitle: 'اسحب وأفلت المستندات هنا &hellip;',
        dropZoneClickTitle: '<br>(أو استخدم زر اختيار المستند)',
        fileActionSettings: {
            removeTitle: 'إزالة المستند',
            uploadTitle: 'رفع المستند',
            uploadRetryTitle: 'Retry upload',
            downloadTitle: 'Download file',
            zoomTitle: 'مشاهدة التفاصيل',
            dragTitle: 'Move / Rearrange',
            indicatorNewTitle: 'لم يتم الرفع بعد',
            indicatorSuccessTitle: 'تم الرفع',
            indicatorErrorTitle: 'خطأ بالرفع',
            indicatorLoadingTitle: 'جارٍ الرفع ...'
        },
        previewZoomButtonTitles: {
            prev: 'View previous file',
            next: 'View next file',
            toggleheader: 'Toggle header',
            fullscreen: 'Toggle full screen',
            borderless: 'Toggle borderless mode',
            close: 'Close detailed preview'
        }
    };
})(window.jQuery);