using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{


    public class BrokerSubOrdinateDetails
    {
        public int Field000 { get; set; } // (int, null)
        public string userid { get; set; } // (varchar(40), not null)
        public string TableName { get; set; } // (varchar(16), not null)
        public string CivilId { get; set; } // (nvarchar(60), null)
        public string BGStatus { get; set; } // (nvarchar(50), null)
        public string AccountStatus { get; set; } // (nvarchar(50), null)
        public string testaccnt { get; set; } // (char(1), null)
        public string TradeLicenseNumber { get; set; } // (nvarchar(15), null)
        public string BrokerName { get; set; } // (nvarchar(180), null)
        public string BrokerFileNumber { get; set; } // (varchar(4), null)
        public string BrokerType { get; set; } // (nvarchar(100), null)
        public string EseBrokerType { get; set; } // (nvarchar(50), null)
        public string BankGuaranteeNo { get; set; } // (varchar(32), not null)
        public DateTime BankGuaranteeExpiryDate { get; set; } // (datetime, null)
    }
    public class BrokerSubOrdinateReq
    {
        public string OrganizationIds { get; set; }
        public int UserId { get; set; }
        public string MCUserId { get; set; }
    }
    //public class GeneralBrokerSubOrdinates
    //{
    //    public int Field000 { get; set; } // (int, null)
    //    public string userid { get; set; } // (varchar(40), not null)
    //    public string TableName { get; set; } // (varchar(16), not null)
    //    public string CivilId { get; set; } // (nvarchar(60), null)
    //    public string BGStatus { get; set; } // (nvarchar(50), null)
    //    public string AccountStatus { get; set; } // (nvarchar(50), null)
    //    public string testaccnt { get; set; } // (char(1), null)
    //    public string TradeLicenseNumber { get; set; } // (nvarchar(15), null)
    //    public string BrokerName { get; set; } // (nvarchar(180), null)
    //    public string BrokerFileNumber { get; set; } // (varchar(4), null)
    //    public string BrokerType { get; set; } // (nvarchar(100), null)
    //    public string EseBrokerType { get; set; } // (nvarchar(50), null)
    //    public string BankGuaranteeNo { get; set; } // (varchar(32), not null)
    //    public DateTime BankGuaranteeExpiryDate { get; set; } // (datetime, null)
    //    public int OrganizationId { get; set; } // (int, not null)
    //    public int OrganizationTypeId { get; set; } // (int, not null)
    //    public string Name { get; set; } // (nvarchar(120), null)
    //    public string OrganizationCode { get; set; } // (varchar(10), null)
    //    public string Description { get; set; } // (nvarchar(120), null)
    //    public string TradeLicenseNumber1 { get; set; } // (nvarchar(15), null)
    //    public DateTime DateCreated { get; set; } // (datetime, null)
    //    public string CreatedBy { get; set; } // (varchar(30), null)
    //    public DateTime DateModified { get; set; } // (datetime, null)
    //    public string ModifiedBy { get; set; } // (varchar(30), null)
    //    public string StateId { get; set; } // (varchar(50), not null)
    //    public int OwnerOrgId { get; set; } // (int, null)
    //    public decimal InsurancePremium { get; set; } // (decimal(18,3), null)
    //    public int ClientConductStatusId { get; set; } // (int, null)
    //    public string PermitNumber { get; set; } // (varchar(35), null)
    //    public int OwnerLocId { get; set; } // (int, null)
    //    public string LocalDescription { get; set; } // (nvarchar(170), null)
    //    public string IsOnlineBroker { get; set; } // (char(1), null)
    //    public string CivilId1 { get; set; } // (varchar(20), null)
    //    public string AuthPerson { get; set; } // (nvarchar(120), null)
    //    public string FirstName { get; set; } // (nvarchar(50), null)
    //    public string LastName { get; set; } // (nvarchar(30), null)
    //    public int OrgIntgType { get; set; } // (int, null)
    //    public string CommercialLicenseNo { get; set; } // (nvarchar(100), null)
    //    public int CommercialLicenseType { get; set; } // (int, null)
    //    public DateTime CommercialLicenseIssueDate { get; set; } // (datetime, null)
    //    public DateTime CommercialLicenseExpiryDate { get; set; } // (datetime, null)
    //    public string ImporterLicenseNo { get; set; } // (nvarchar(100), null)
    //    public int ImporterLicenseType { get; set; } // (int, null)
    //    public DateTime ImporterLicenseIssueDate { get; set; } // (datetime, null)
    //    public DateTime ImporterLicenseExpiryDate { get; set; } // (datetime, null)
    //    public int CommercialLicenseSubType { get; set; } // (int, null)
    //    public string CommercialName { get; set; } // (nvarchar(120), null)
    //    public string CommercialRecord { get; set; } // (nvarchar(15), null)
    //    public long TotalTransit { get; set; } // (bigint, null)
    //    public long TotalImport { get; set; } // (bigint, null)
    //    public long TotalExport { get; set; } // (bigint, null)
    //    public long TotalTranshipment { get; set; } // (bigint, null)
    //    public long TotalTransit_ARC { get; set; } // (bigint, null)
    //    public long TotalImport_ARC { get; set; } // (bigint, null)
    //    public long TotalExport_ARC { get; set; } // (bigint, null)
    //    public long TotalTranshipment_ARC { get; set; } // (bigint, null)
    //    public string OGAAllowedPorts { get; set; } // (varchar(250), null)
    //    public string IsIndustrial { get; set; } // (char(1), null)
    //    public string IndustrialLicenseNo { get; set; } // (varchar(50), null)
    //    public DateTime IndIssueDate { get; set; } // (datetime, null)
    //    public DateTime IndExpiryDate { get; set; } // (datetime, null)
    //    public string IndRegNo { get; set; } // (varchar(50), null)
    //    public DateTime IndRegIssuanceDate { get; set; } // (datetime, null)
    //    public int AllowSubmitWOGCSFee { get; set; } // (int, null)
    //    public string IsManual { get; set; } // (char(1), null)
    //    public string MOCIDataSynch { get; set; } // (char(1), null)
    //    public string OGACodes { get; set; } // (varchar(50), null)
    //    public string LegalEntity { get; set; } // (varchar(50), null)
    //    public int BrokerOrgDetailId { get; set; } // (int, null)
    //    public int BrokerOrgId { get; set; } // (int, null)
    //    public int BrokerTypeId { get; set; } // (int, null)
    //    public string LicenseNo { get; set; } // (nvarchar(50), null)
    //    public string ContractNo { get; set; } // (nvarchar(50), null)
    //    public string Notes { get; set; } // (nvarchar(400), null)
    //    public string ReasonsForBlocking { get; set; } // (nvarchar(120), null)
    //    public DateTime LastBlockedDate { get; set; } // (datetime, null)
    //    public string ReasonsForActivation { get; set; } // (nvarchar(120), null)
    //    public DateTime LastActivatedDate { get; set; } // (datetime, null)
    //    public DateTime DateCreated1 { get; set; } // (datetime, null)
    //    public string CreatedBy1 { get; set; } // (nvarchar(50), null)
    //    public DateTime DateModified1 { get; set; } // (datetime, null)
    //    public string ModifiedBy1 { get; set; } // (nvarchar(50), null)
    //    public string StateId1 { get; set; } // (nvarchar(50), null)
    //    public int OwnerOrgId1 { get; set; } // (int, null)
    //    public int OwnerLocId1 { get; set; } // (int, null)
    //    public int BrokerWorkingStatusTypeId { get; set; } // (int, null)
    //    public string OtherReasonsForDeactivation { get; set; } // (nvarchar(120), null)
    //    public string CivilId2 { get; set; } // (nvarchar(60), null)
    //    public string PassportNo { get; set; } // (nvarchar(100), null)
    //    public DateTime IDExpiryDate { get; set; } // (datetime, null)
    //    public DateTime PassportExpiryDate { get; set; } // (datetime, null)
    //    public int ActivationReasonId { get; set; } // (int, null)
    //    public int CancellationReasonId { get; set; } // (int, null)
    //    public string CancellationReason { get; set; } // (nvarchar(1000), null)
    //    public int BrokBGDetailId { get; set; } // (int, null)
    //    public int BrokerOrgId1 { get; set; } // (int, null)
    //    public string BGNo { get; set; } // (varchar(32), null)
    //    public int BankId { get; set; } // (int, null)
    //    public DateTime BGIssueDt { get; set; } // (datetime, null)
    //    public DateTime BGExpiryDt { get; set; } // (datetime, null)
    //    public decimal BGAmount { get; set; } // (decimal(18,0), null)
    //    public string BGRemarks { get; set; } // (varchar(100), null)
    //    public DateTime DateCreated2 { get; set; } // (datetime, null)
    //    public string CreatedBy2 { get; set; } // (nvarchar(50), null)
    //    public DateTime DateModified2 { get; set; } // (datetime, null)
    //    public string ModifiedBy2 { get; set; } // (nvarchar(50), null)
    //    public string StateId2 { get; set; } // (nvarchar(50), null)
    //    public int OwnerOrgId2 { get; set; } // (int, null)
    //    public int OwnerLocId2 { get; set; } // (int, null)
    //    public string BGBrokerType { get; set; } // (varchar(5), null)
    //    public int TradeLicenseId { get; set; } // (int, null)
    //    public int BrokerOrgDetailId1 { get; set; } // (int, null)
    //    public int BrokLicenseDetailId { get; set; } // (int, null)
    //    public string HoldReason { get; set; } // (nvarchar(1000), null)
    //    public string SeizeReason { get; set; } // (nvarchar(1000), null)
    //    public string ReleaseReason { get; set; } // (nvarchar(1000), null)
    //    public int CompleteExpire { get; set; } // (int, null)
    //    public int OrganizationId1 { get; set; } // (int, null)
    //    public int SubOrgId { get; set; } // (int, null)
    //    public int MainOrgId { get; set; } // (int, null)
    //    public int ChildOrgId { get; set; } // (int, null)
    //    public DateTime DateCreated3 { get; set; } // (datetime, null)
    //    public string CreatedBy3 { get; set; } // (nvarchar(50), null)
    //    public DateTime DateModified3 { get; set; } // (datetime, null)
    //    public string ModifiedBy3 { get; set; } // (nvarchar(50), null)
    //    public string StateId3 { get; set; } // (nvarchar(50), null)
    //    public int OwnerOrgId3 { get; set; } // (int, null)
    //    public int OwnerLocId3 { get; set; } // (int, null)
    //    public DateTime TransferredDate { get; set; } // (datetime, null)
    //    public int TransferOrg { get; set; } // (int, null)
    //    public string UserId { get; set; } // (varchar(40), null)
    //    public string TransferredBy { get; set; } // (nvarchar(200), null)
    //    public int TypeId { get; set; } // (int, null)
    //    public int TypeTypeId { get; set; } // (int, null)
    //    public string Name1 { get; set; } // (nvarchar(50), null)
    //    public string Description1 { get; set; } // (nvarchar(100), null)
    //    public string DataProfileClassId { get; set; } // (varchar(50), null)
    //    public int ParentId { get; set; } // (int, null)
    //    public string Code { get; set; } // (nvarchar(50), null)
    //    public DateTime DateCreated4 { get; set; } // (datetime, null)
    //    public string CreatedBy4 { get; set; } // (varchar(30), null)
    //    public DateTime DateModified4 { get; set; } // (datetime, null)
    //    public string ModifiedBy4 { get; set; } // (varchar(30), null)
    //    public string StateId4 { get; set; } // (varchar(50), null)
    //    public int OwnerOrgId4 { get; set; } // (int, null)
    //    public int OwnerLocId4 { get; set; } // (int, null)
    //    public string LocalDescription1 { get; set; } // (nvarchar(100), null)
    //    public int TypeId1 { get; set; } // (int, null)
    //    public string Name2 { get; set; } // (nvarchar(100), null)
    //    public string Description2 { get; set; } // (nvarchar(100), null)
    //    public string CreatedBy5 { get; set; } // (varchar(30), null)
    //    public int BrokLicenseDetailId1 { get; set; } // (int, null)
    //    public int BrokerOrgId2 { get; set; } // (int, null)
    //    public string LicenseNo1 { get; set; } // (varchar(35), null)
    //    public DateTime DtOfIssue { get; set; } // (datetime, null)
    //    public DateTime DtOfExpiry { get; set; } // (datetime, null)
    //    public string Remarks { get; set; } // (varchar(100), null)
    //    public DateTime DateCreated6 { get; set; } // (datetime, null)
    //    public string CreatedBy6 { get; set; } // (nvarchar(50), null)
    //    public DateTime DateModified6 { get; set; } // (datetime, null)
    //    public string ModifiedBy6 { get; set; } // (nvarchar(50), null)
    //    public string StateId6 { get; set; } // (nvarchar(50), null)
    //    public int OwnerOrgId6 { get; set; } // (int, null)
    //    public int OwnerLocId6 { get; set; } // (int, null)
    //    public string BrokerFileNumber1 { get; set; } // (varchar(4), null)
    //    public string DataProfileClassWorkflowStateId_Old { get; set; } // (varchar(50), null)
    //    public string DataProfileClassId1 { get; set; } // (varchar(50), null)
    //    public string StateId5 { get; set; } // (varchar(50), null)
    //    public string StateName { get; set; } // (varchar(50), null)
    //    public DateTime DateCreated7 { get; set; } // (datetime, null)
    //    public string CreatedBy7 { get; set; } // (varchar(30), null)
    //    public DateTime DateModified7 { get; set; } // (datetime, null)
    //    public string ModifiedBy7 { get; set; } // (varchar(30), null)
    //    public string StateDescription { get; set; } // (varchar(256), null)
    //    public string OwnerOrgId8 { get; set; } // (varchar(35), null)
    //    public string StateForView { get; set; } // (varchar(50), null)
    //    public string OwnerLocId8 { get; set; } // (varchar(35), null)
    //    public int DataProfileClassWorkflowStateId { get; set; } // (int, null)
    //    public string DataProfileClassWorkflowStateId_Old1 { get; set; } // (varchar(50), null)
    //    public string StateId9 { get; set; } // (varchar(50), null)
    //    public string StateName9 { get; set; } // (nvarchar(50), null)
    //    public string StateDescription9 { get; set; } // (nvarchar(256), null)
    //    public int DataProfileClassWorkflowStateId2 { get; set; } // (int, null)
    //    public int OrganizationId2 { get; set; } // (int, null)
    //    public string Name9 { get; set; } // (nvarchar(180), null)
    //    public string Description9 { get; set; } // (nvarchar(180), null)
    //    public string AuthPerson9 { get; set; } // (nvarchar(120), null)
    //    public string UserId9 { get; set; } // (varchar(40), null)
    //    public int PersonalId { get; set; } // (int, null)
    //    public string Name8 { get; set; } // (varchar(255), null)
    //    public string Description8 { get; set; } // (varchar(100), null)
    //    public string Password { get; set; } // (varchar(100), null)
    //    public string Token { get; set; } // (varchar(50), null)
    //    public string Groups { get; set; } // (varchar(500), null)
    //    public string Roles { get; set; } // (varchar(1000), null)
    //    public DateTime LastLogonTime { get; set; } // (datetime, null)
    //    public int OrganizationId3 { get; set; } // (int, null)
    //    public int DepartmentId { get; set; } // (int, null)
    //    public int SectionId { get; set; } // (int, null)
    //    public string UnitId { get; set; } // (varchar(35), null)
    //    public string OrganizationType { get; set; } // (varchar(50), null)
    //    public string AccountStatus1 { get; set; } // (char(1), null)
    //    public DateTime LoginExpiryDate { get; set; } // (datetime, null)
    //    public DateTime DateCreated9 { get; set; } // (datetime, null)
    //    public string CreatedBy9 { get; set; } // (varchar(30), null)
    //    public DateTime DateModified9 { get; set; } // (datetime, null)
    //    public string ModifiedBy9 { get; set; } // (varchar(30), null)
    //    public string StateId10 { get; set; } // (varchar(50), null)
    //    public int OwnerOrgId9 { get; set; } // (int, null)
    //    public string ActiveSessionId { get; set; } // (varchar(40), null)
    //    public DateTime LastHitTime { get; set; } // (datetime, null)
    //    public string PersonalCode { get; set; } // (nvarchar(50), null)
    //    public string ThemeId { get; set; } // (varchar(35), null)
    //    public int LoginPortId { get; set; } // (int, null)
    //    public string AllowedClientIp { get; set; } // (varchar(50), null)
    //    public int OwnerLocId7 { get; set; } // (int, null)
    //    public string LatestUpdates { get; set; } // (char(1), null)
    //    public string TwoFactorAuth { get; set; } // (char(1), null)
    //    public int IsLocked { get; set; } // (int, null)
    //    public string IsDisabled { get; set; } // (char(1), null)
    //    public DateTime LockedPeriod { get; set; } // (datetime, null)
    //    public int TIMEZONE { get; set; } // (int, null)
    //    public string old_accountstatus { get; set; } // (char(1), null)
    //    public DateTime loginexpirydate_old { get; set; } // (datetime, null)
    //    public int CustomerNumber { get; set; } // (int, null)
    //    public string FingerPrintToken { get; set; } // (varchar(50), null)
    //    public DateTime FingerPrintTokenExpiry { get; set; } // (datetime, null)
    //    public string IsGeoUser { get; set; } // (char(1), null)
    //    public string EMAILID { get; set; } // (varchar(100), null)
    //    public int AllowedDataTamperAttempts { get; set; } // (int, null)
    //    public string IsEmailVerified { get; set; } // (char(1), null)
    //}

}